#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

counter = 0
list_nums = [0]
x = 1
y = 0
z = 0

while list_nums[-1] <= 4000000:
    if x >= y:
        z = x + y
        list_nums.append(z)
        counter += 1
    print(list_nums)

    if z >= x:
        y = z + x
        list_nums.append(y)
        counter +=1
    print(list_nums)

    if y >= z:
        x = y + z
        list_nums.append(x)
        counter += 1
    print(list_nums)

no = list_nums.pop()

summing_list = []
for x in list_nums:
    if x % 2 == 0:
        summing_list.append(x)

print("the sum hopefully is: " + str(sum(summing_list)))
